overviewText 	= 	"Testing map for Overthrow. Note: Uses ALOT of editor objects, so expect it to run poorly.";
OnLoadMission	=	"Those who make peaceful revolution impossible will make violent revolution inevitable. - JFK, 1962";
OnLoadName 		= 	"Dead's Overthrow: VR";

class OT_missionCustomization {
	startCameraPos[] = {11646.6,6406.52,2}; //Start screen camera position
	startCameraTarget[] = {13808.2,6387.16,0}; //Point where start screen camera faces
};