overviewText 	= 	"Altis, the main island of the Republic of Altis and Stratis, is located in the Mediterranean Sea to the east of Malta. As of 2040, Altis is currently under occupation by NATO forces following a brutal civil war a half decade prior, and the nation is still recovering. NATO originally occupied the country under the promise of a complete withdrawal of forces and return to local democratic rule; despite this, NATO soldiers still occupy the island's military installations. The economy continues to stagnate and citizens are becoming increasingly angry at the lack of local autonomy.";
OnLoadMission	=	"Those who make peaceful revolution impossible will make violent revolution inevitable. - JFK, 1962";
OnLoadName 		= 	"Dead's Overthrow: Altis";

import OT_missionCustomization_base;
class OT_missionCustomization : OT_missionCustomization_base {
	startCameraPos[] = {11646.6,6406.52,2};
	startCameraTarget[] = {13808.2,6387.16,0};
};